### ISSUE TITLE
Validation for permalinks to prevent non-English characters

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#115]
One user asked us for validation for permalinks.

They sometimes find that non-English characters are entered into the permalink (perhaps automatically from the title).

**Comment by andergmartins** [comment]
I'm reopening it because the client found a bug using the Classic Editor. If you publish the post with english chars only in the URL but edit it later, the Update button doesn't trigger the same verification we don in the "Publish". That means we can update a post and insert "invalid" chars in the URL, like 漢語.

**Comment by andergmartins** [comment]
Ok, after testing more this is a bug in the checklist, for any task, not on this specific new feature. I'm closing this again and reopening another ticket for the new issue.
