### ISSUE TITLE
Change the order of items in the checklist

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Checklists#172]
We've had one customer request the ability change the order of items in the checklist.

We'll need to think through the best way to do this. I think the main checklist settings page should stay the same. This may require a new settings area.

**Comment by andergmartins** [comment]
Just adding a drag-and-drop behavior to the Checklists settings page wouldn't be enough for now?

I would like to suggest this new interface, where the items are sortable in the "Enabled" list:

<img width="1281" alt="Screen Shot 2020-07-27 at 14 07 19" src="https://user-images.githubusercontent.com/407131/88570745-f8c6fa80-d012-11ea-8c06-5e4041eb60c4.png">


<img width="1280" alt="Screen Shot 2020-07-27 at 14 10 06" src="https://user-images.githubusercontent.com/407131/88570756-febcdb80-d012-11ea-91f7-5d00917091ec.png">

**Comment by stevejburge** [comment]
@andergmartins OK, that's 100% a better idea than anything I have had!

**Comment by julianactrl** [comment]
@stevejburge  and @andergmartins ,
I just pushed the changes for this issue on development branch.

**Comment by andergmartins** [comment]
Hi @julianactrl thank you for the contribution. I tested the changes and it works well on the settings page, but I don't see the items displayed in the selected order on the post edit page. Please, could you double-check and make sure the order we set on the settings page will be used to display the items in the metabox?

Feel free to ping us if you have any questions.

I have moved the commit you sent to a new branch: `feature-172-change-checklists-order`, and reverted it in the development branch. Please, could you commit your new changes to this new branch instead of directly in the development branch?

Then after finishing the changes, please could you create a pull request (targeting the development branch) and add me as a reviewer? 

Thanks
