### ISSUE TITLE
Uncheck and save not available for users with no publish_post capability

### ISSUE THREAD

**Issue by pmavila** [publishpress/PublishPress-Checklists#286]
**The problem:** 
A reviewer user that has no publish_post capability unchecks a custom checklist item, but then he is stuck and cannot save because there's is no "save" button that is usually there for users with publish_post capability.

Scenario:

1. An author creates a new post and saves the post as "pending for review"
2. The reviewer logs in approve the post by checking a checklist item and clicks on "submit for review"
3. The reviewer then changes his mind and tries to uncheck the checklist item, but the reviewer cannot save it now because he has no save button and cannot use the "Submit for review" because a checklist item is left "unchecked"

![image](https://user-images.githubusercontent.com/11922052/125597073-4936375e-4309-459e-b77f-580ba17d99ec.png)

**Comment by olatechpro** [comment]
@stevejburge I really don't understand what the fixes for this issues should be or could it be outdated?

For example, we now have a feature that enable option to select roles that could skip the checklist restriction.

But if this is about another issue that still exist, what's the suggested fix suppose to be since that capability is required to publish post and not sure we're altering that?

**Comment by stevejburge** [comment]
@olatechpro Good point. I'm happy to close this
